### ISSUE TITLE
As a user, I want to be able to add new AWS credentials to create a new System

### ISSUE THREAD

**Issue by lisagumerman** [sunshower-io/sunshower#39]
Workflow
- [x] see button to add creds
- [x] select cloud (AWS)
- [x] see security group recommendation
- [x] enter IAM creds
- [x] verify that creds work
- [x] review and name System
- [x] save
- [x] be dropped into a view of my system

**Comment by lisagumerman** [comment]
this is hooked up in terms of UI elements, we still need services & I'm working on navigating with the stepper

**Comment by lisagumerman** [comment]
TODO: Lisa needs to verify. For now, just ensure that we can go through, save everything & be redirected to inventory

**Comment by josiahhaswell** [comment]
Can someone test this and file a defect report? It's in the latest master and docker.

**Comment by lisagumerman** [comment]
@josiahhaswell just filed a bug: https://github.com/sunshower-io/sunshower/issues/62
