### ISSUE TITLE
Document Sunshower site release process

### ISSUE THREAD

**Issue by josiahhaswell** [sunshower-io/sunshower#48]
As a Sunshower Documentation Developer, I would like to know how to build the website

- [ ] Check out https://sunshower-io.github.io/sunshower.io/ using Git
- [ ] Create Github Documentation Task (ATM:DOCS-XXXX)
- [ ] Build documentation site
- [ ] Create a new branch (ATM:DOCS-XXXX)
- [ ] Make an edit on your branch
- [ ] Submit Pull Request to sunshower.io/master
- [ ] Document all steps with Markdown in sunshower.io wiki

**Comment by lisagumerman** [comment]
Going to consider this to-did
