### ISSUE TITLE
Tag-Based Grouping

### ISSUE THREAD

**Issue by josiahhaswell** [sunshower-io/sunshower#61]
As a user, I would like to be able to view systems by shared tags.

Acceptance Criteria:

- [ ] All tags with the same key and value form an implicit group.
- [ ] Any time I tag a node with a new tag, any other node that shares that key/value pair is added to a group of all nodes sharing that tag.
- [ ] Each implicit group can be assigned a color
- [ ] If an implicit group exists with a different color, attempting to change the color generates a warning message and lists the elements of that implicit group.
- [ ] Every implicit group in a system generates a corresponding color element in the topology navigator menu
- [ ] The tag panel can add tags

**Comment by lisagumerman** [comment]
Blocked by https://github.com/sunshower-io/sunshower/issues/78
