### ISSUE TITLE
Implement Activation

### ISSUE THREAD

**Issue by josiahhaswell** [sunshower-io/sunshower#68]
As an administrator with a newly-installed instance of Sunshower, I would like to:

- [x] Be directed to the activation page if sunshower is not activated
- [x] Supply admin username, admin email, and admin password to sunshower
- [x] Be directed to sunshower home screen upon successful activation
- [x]  All text must be localized
- [x] Loading must be implemented
- [x] Styles must be implemented
- [x] Non-developer must test
- [x] unit tests
- [x] Password length must be between 8 and 30
- [x] Email address must be validated
- [x] Username must be between 5 and 45 characters long
- [x] Left-hand side should contain friendly text
- [x] Right-hand side should contain form+gradient

**Comment by lisagumerman** [comment]
ON IT

**Comment by lisagumerman** [comment]
Whatcha mean by "loading must be implemented"? I saw that the button had a spot for loading -- do you mean that, or a full page reload?

**Comment by josiahhaswell** [comment]
Yeah--some sort of indicator that the application is doing something--probably a button or something.  It's possible that just redirecting to the page that already has a loader is adequate, but I think we'll want the button

**Comment by haswellj** [comment]
Done
